[OSEv3:children]
masters
etcd
nodes

[OSEv3:vars]
ansible_ssh_user=centos
ansible_sudo=true
ansible_become=true

debug_level=4

openshift_deployment_type=origin

openshift_release=v3.9
openshift_image_tag=v3.9.0

# This is needed because by default the installer registry.access.redhat.com
# even if the deployment type is origin:
# https://github.com/openshift/openshift-ansible/issues/7808
#
osm_etcd_image=registry.redhat.io/rhel7/etcd

# Only needed for Container Platform
#ocp_version=3.9

openshift_cloudprovider_kind=aws
openshift_clusterid=sdb_cluster_1

openshift_cloudprovider_aws_access_key="{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
openshift_cloudprovider_aws_secret_key="{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"

# Using the containerized release because upstream in particular is focusing
# on delivering images rather than rpms
containerized=true

os_sdn_network_plugin_name='redhat/openshift-ovs-multitenant'

openshift_install_examples=true

openshift_docker_options='--selinux-enabled --insecure-registry 172.30.0.0/16'
openshift_master_identity_providers=[{'name': 'htpasswd_auth', 'login': 'true', 'challenge': 'true', 'kind': 'HTPasswdPasswordIdentityProvider', 'filename': '/etc/origin/master/htpasswd'}]

osm_cluster_network_cidr=10.128.0.0/14
openshift_portal_net=172.30.0.0/16


#openshift_disable_check=disk_availability,docker_storage,memory_availability

openshift_repos_enable_testing=True

[masters]
ec2-54-210-205-226.compute-1.amazonaws.com

[etcd]
ec2-54-210-205-226.compute-1.amazonaws.com

[nodes]
ec2-54-210-205-226.compute-1.amazonaws.com openshift_node_labels="{'region':'infra','zone':'east'}" openshift_schedulable=true
ec2-52-87-203-168.compute-1.amazonaws.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
ec2-54-144-236-48.compute-1.amazonaws.com openshift_node_labels="{'region': 'primary', 'zone': 'east'}"
